# Computing and Visualizing KPIs using Python

In [1]:
# Loading data
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
bank_marketing = fetch_ucirepo(id=222) 
  
# data (as pandas dataframes) 
X = bank_marketing.data.features 
y = bank_marketing.data.targets 
  
# metadata 
print(bank_marketing.metadata) 
  
# variable information 
print(bank_marketing.variables)

{'uci_id': 222, 'name': 'Bank Marketing', 'repository_url': 'https://archive.ics.uci.edu/dataset/222/bank+marketing', 'data_url': 'https://archive.ics.uci.edu/static/public/222/data.csv', 'abstract': 'The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe a term deposit (variable y).', 'area': 'Business', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 45211, 'num_features': 16, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Occupation', 'Marital Status', 'Education Level'], 'target_col': ['y'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Fri Aug 18 2023', 'dataset_doi': '10.24432/C5K306', 'creators': ['S. Moro', 'P. Rita', 'P. Cortez'], 'intro_paper': {'ID': 277, 'type': 'NATIVE', 'title': 'A data-driven approach to predict the success of bank telemarketing', 'authors': 'Sérgio Moro, P. Cortez, P. Rita', 'venue': 'Decision Support Systems', 'year': 2014, 'journal': None, 'DOI': '10.1016/j.dss.2014.03.001', 'URL': 'https://www.semanticscholar.org/paper/cab86052882d126d43f72108c6cb41b295cc8a9e', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': "The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed. \n\nThere are four datasets: \n1) bank-additional-full.csv with all examples (41188) and 20 inputs, ordered by date (from May 2008 to November 2010), very close to the data analyzed in [Moro et al., 2014]\n2) bank-additional.csv with 10% of the examples (4119), randomly selected from 1), and 20 inputs.\n3) bank-full.csv with all examples and 17 inputs, ordered by date (older version of this dataset with less inputs). \n4) bank.csv with 10% of the examples and 17 inputs, randomly selected from 3 (older version of this dataset with less inputs). \nThe smallest datasets are provided to test more computationally demanding machine learning algorithms (e.g., SVM). \n\nThe classification goal is to predict if the client will subscribe (yes/no) a term deposit (variable y).", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Input variables:\n   # bank client data:\n   1 - age (numeric)\n   2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",\n                                       "blue-collar","self-employed","retired","technician","services") \n   3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)\n   4 - education (categorical: "unknown","secondary","primary","tertiary")\n   5 - default: has credit in default? (binary: "yes","no")\n   6 - balance: average yearly balance, in euros (numeric) \n   7 - housing: has housing loan? (binary: "yes","no")\n   8 - loan: has personal loan? (binary: "yes","no")\n   # related with the last contact of the current campaign:\n   9 - contact: contact communication type (categorical: "unknown","telephone","cellular") \n  10 - day: last contact day of the month (numeric)\n  11 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")\n  12 - duration: last contact duration, in seconds (numeric)\n   # other attributes:\n  13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)\n  14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)\n  15 - previous: number of contacts performed before this campaign and for this client (numeric)\n  16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")\n\n  Output variable (desired target):\n  17 - y - has the client subscribed a term deposit? (binary: "yes","no")\n', 'citation': None}}
           name     role         type      demographic  \
0           age  Feature      Integer              Age
1           job  Feature  Categorical       Occupation
2       marital  Feature  Categorical   Marital Status
3     education  Feature  Categorical  Education Level
4       default  Feature       Binary              NaN
5       balance  Feature      Integer              NaN
6       housing  Feature       Binary              NaN
7          loan  Feature       Binary              NaN
8       contact  Feature  Categorical              NaN
9   day_of_week  Feature         Date              NaN
10        month  Feature         Date              NaN
11     duration  Feature      Integer              NaN
12     campaign  Feature      Integer              NaN
13        pdays  Feature      Integer              NaN
14     previous  Feature      Integer              NaN
15     poutcome  Feature  Categorical              NaN
16            y   Target       Binary              NaN

                                          description  units missing_values
0                                                 NaN    NaN             no
1   type of job (categorical: 'admin.','blue-colla...    NaN             no
2   marital status (categorical: 'divorced','marri...    NaN             no
3   (categorical: 'basic.4y','basic.6y','basic.9y'...    NaN             no
4                              has credit in default?    NaN             no
5                              average yearly balance  euros             no
6                                   has housing loan?    NaN             no
7                                  has personal loan?    NaN             no
8   contact communication type (categorical: 'cell...    NaN            yes
9                        last contact day of the week    NaN             no
10  last contact month of year (categorical: 'jan'...    NaN             no
11   last contact duration, in seconds (numeric). ...    NaN             no
12  number of contacts performed during this campa...    NaN             no
13  number of days that passed by after the client...    NaN            yes
14  number of contacts performed before this campa...    NaN             no
15  outcome of the previous marketing campaign (ca...    NaN            yes
16          has the client subscribed a term deposit?    NaN             no

In [2]:
# Consstruct dataframe from X,y
import pandas as pd
df = pd.DataFrame(X)
df['y'] = y
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN,no
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN,no
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN,no
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN,no

In [3]:
# Create a conversion data column
df['conversion'] = df['y'].apply(lambda x: 1 if x == 'yes' else 0)
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome,y,conversion
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN,no,0
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN,no,0
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN,no,0
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN,no,0
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN,no,0

## Aggreate converrtion rate

In [4]:
print(f"Total Conversions: {df.conversion.sum()} out of {df.shape[0]} clients")

Total Conversions: 5289 out of 45211 clients

In [5]:
print(f"The conversion rate is: {df.conversion.mean():.2%}")

The conversion rate is: 11.70%

## Conversion rate by age

In [6]:
conversion_rate_by_age = df.groupby('age')['conversion'].mean()*100
conversion_rate_by_age

age
18     58.333333
19     31.428571
20     30.000000
21     27.848101
22     31.007752
         ...
90    100.000000
92    100.000000
93    100.000000
94      0.000000
95     50.000000
Name: conversion, Length: 77, dtype: float64

In [7]:
# Visualize conversion rate by age using plotly
import plotly.express as px
figsize=(10,7)
fig = px.line(conversion_rate_by_age, 
              x=conversion_rate_by_age.index, 
              y=conversion_rate_by_age.values, 
              title='Conversion Rate by Age', 
              labels={'x':'Age', 'y':'Conversion Rate (%)'},
              template='ggplot2'
              )
fig.show()

In [8]:
# To group bank clients into six different groups, based on their age—between 18 and 30, between 30 and 40, between 40 and 50, between 50 and 60, between 60 and 70, and 70 and older
age_bins = [18, 30, 40, 50, 60, 70, float('inf')]
age_labels = ['18-30', '30-40', '40-50', '50-60', '60-70', '70+']
df['age_group'] = pd.cut(df['age'], bins=age_bins, labels=age_labels, right=False)
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day_of_week,month,duration,campaign,pdays,previous,poutcome,y,conversion,age_group
0,58,management,married,tertiary,no,2143,yes,no,NaN,5,may,261,1,-1,0,NaN,no,0,50-60
1,44,technician,single,secondary,no,29,yes,no,NaN,5,may,151,1,-1,0,NaN,no,0,40-50
2,33,entrepreneur,married,secondary,no,2,yes,yes,NaN,5,may,76,1,-1,0,NaN,no,0,30-40
3,47,blue-collar,married,NaN,no,1506,yes,no,NaN,5,may,92,1,-1,0,NaN,no,0,40-50
4,33,NaN,single,NaN,no,1,no,no,NaN,5,may,198,1,-1,0,NaN,no,0,30-40

In [9]:
# Create conversion rate by age group
conversion_rate_by_age_group = df.groupby('age_group')['conversion'].mean()*100
conversion_rate_by_age_group

age_group
18-30    17.599090
30-40    10.575488
40-50     9.120549
50-60     9.334126
60-70    29.674797
70+      42.418773
Name: conversion, dtype: float64

In [10]:
# Visualize conversion rate by age group using plotly
from plotly import colors


figsize=(10,7)
fig = px.bar(conversion_rate_by_age_group,
            x=conversion_rate_by_age_group.index, 
            y=conversion_rate_by_age_group.values, 
            title='Conversion Rate by Age Group', 
            labels={'x':'Age Group', 'y':'Conversion Rate (%)'},
            template='ggplot2',
            color_discrete_sequence=colors.qualitative.Pastel
            )
fig.show()

## Non conversions vs conversions

In [11]:
df['marital'].value_counts(dropna=False)

marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

In [12]:
pd.pivot_table(df,values='y', index='marital', columns='conversion', aggfunc=len)

conversion      0     1
marital
divorced     4585   622
married     24459  2755
single      10878  1912

In [13]:
# Create a pie chart to visualize the distribution of marital status among converters and non-converters
conversion_marital_counts = df.groupby(['marital', 'conversion']).size().reset_index(name='count')
fig = px.pie(conversion_marital_counts,
             names='marital',
             values='count',
             title='Marital Status Distribution among Converters and Non-Converters',
             template='ggplot2',
             color_discrete_sequence=colors.qualitative.Pastel
             )
fig.show()

In [14]:
marital_by_conversion = df.groupby(['conversion', 'marital']).size().unstack()

from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=1, cols=2, specs=[[{'type': 'pie'}, {'type': 'pie'}]],
                    subplot_titles=['Non-Conversion (0)', 'Conversion (1)'])

for i, conversion in enumerate(marital_by_conversion.index):
    fig.add_trace(
        go.Pie(
            labels=marital_by_conversion.columns,
            values=marital_by_conversion.loc[conversion],
            name=str(conversion),
            textinfo='percent+label',
            marker=dict(colors=colors.qualitative.Pastel)
        ),
        row=1, col=i+1
    )

fig.update_layout(
    title='Marital Status Distribution by Conversion',
    template='ggplot2'
)
fig.show()

# Conversion rate by age and marital status

In [15]:
df.groupby(['age_group', 'marital'])['conversion'].sum()

age_group  marital
18-30      divorced     11
           married     123
           single      794
30-40      divorced    158
           married     913
           single      842
40-50      divorced    175
           married     678
           single      210
50-60      divorced    160
           married     572
           single       53
60-70      divorced     63
           married     292
           single       10
70+        divorced     55
           married     177
           single        3
Name: conversion, dtype: int64

In [16]:
df.groupby(['age_group', 'marital'])['conversion'].sum().unstack('marital').fillna(0)

marital    divorced  married  single
age_group
18-30            11      123     794
30-40           158      913     842
40-50           175      678     210
50-60           160      572      53
60-70            63      292      10
70+              55      177       3

In [17]:
age_marital_df = df.groupby(['age_group', 'marital'])['conversion'].sum().unstack('marital').fillna(0)
age_marital_df

marital    divorced  married  single
age_group
18-30            11      123     794
30-40           158      913     842
40-50           175      678     210
50-60           160      572      53
60-70            63      292      10
70+              55      177       3

In [18]:
age_marital_df = age_marital_df.divide(df.groupby(by='age_group')['conversion'].count(), axis=0)
age_marital_df

marital    divorced   married    single
age_group
18-30      0.002086  0.023326  0.150578
30-40      0.008735  0.050473  0.046548
40-50      0.015015  0.058172  0.018018
50-60      0.019025  0.068014  0.006302
60-70      0.051220  0.237398  0.008130
70+        0.099278  0.319495  0.005415

In [19]:
plot_df = age_marital_df.loc[age_labels].mul(100).reset_index()

fig = px.bar(
    plot_df,
    x='age_group',
    y=['divorced', 'married', 'single'],
    barmode='group',
    title='Conversion rates by Age & Marital Status',
    labels={
        'age_group': 'age group',
        'value': 'conversion rate (%)',
        'variable': 'marital status'
    },
    template='ggplot2',
    color_discrete_sequence=colors.qualitative.Pastel
)

fig.show()

In [20]:
fig = px.bar(
    age_marital_df.loc[age_labels].mul(100).reset_index(),
    x='age_group',
    y=['divorced', 'married', 'single'],
    barmode='stack',
    title='Conversion rates by Age & Marital Status',
    labels={
        'age_group': 'age group',
        'value': 'conversion rate (%)',
        'variable': 'marital status'
    },
    template='ggplot2',
    color_discrete_sequence=colors.qualitative.Pastel
)

fig.show()